/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import MODEL.Patient; 
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;



/**
 *
 * @author apple
 */
public class NewJPanel extends javax.swing.JPanel {
private Patient patient;  
private JPanel bottomPanel;
    
    
    
    
    
    
    

    /**
     * Creates new form NewJPanel
     */


    public NewJPanel(JPanel bottomPanel) {
        this.bottomPanel = bottomPanel;
        initComponents();
//          bottomPanel = new javax.swing.JPanel();
//        bottomPanel.setLayout(new java.awt.CardLayout());
////        jSplitPane1.setRightComponent(bottomPanel);
////        bottomPanel.setLayout(new java.awt.CardLayout());
//jSplitPane1 = new javax.swing.JSplitPane();
//jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
//jSplitPane1.setRightComponent(bottomPanel);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameLabel = new javax.swing.JLabel();
        lnameTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        msgLabel = new javax.swing.JLabel();
        msgTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        patientTypeLabel = new javax.swing.JLabel();
        patientTypeComboBox = new javax.swing.JComboBox<>();
        imageLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 151, 38));
        setPreferredSize(new java.awt.Dimension(750, 637));

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        titleLabel.setText("Patient Registration Form");

        fnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fnameLabel.setText("First Name");

        fnameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextFieldActionPerformed(evt);
            }
        });
        fnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameTextFieldKeyReleased(evt);
            }
        });

        lnameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lnameLabel.setText("Last Name");

        lnameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTextFieldActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ageLabel.setText("Age");

        ageTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyPressed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        emailTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyPressed(evt);
            }
        });

        msgLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        msgLabel.setText("Message");

        msgTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        msgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTextFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        genderLabel.setText("Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        patientTypeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        patientTypeLabel.setText("Patient type");

        patientTypeComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        patientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type ", "Adult", "Child", "Senior Citizen", " " }));

        imageLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        imageLabel.setText("Upload Image");

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton2.setText("Browse File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(204, 204, 255));
        submitButton.setFont(new java.awt.Font("Helvetica Neue", 0, 23)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        submitButton.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                submitButtonVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ageLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(lnameLabel)
                                    .addComponent(msgLabel)
                                    .addComponent(genderLabel)
                                    .addComponent(fnameLabel)
                                    .addComponent(patientTypeLabel)
                                    .addComponent(imageLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2)
                                    .addComponent(fnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnameTextField)
                                    .addComponent(msgTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton2)
                                    .addComponent(emailTextField)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(submitButton)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fnameLabel)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ageLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel)
                    .addComponent(jRadioButton1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fnameTextFieldActionPerformed

    private void fnameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameTextFieldKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_fnameTextFieldKeyPressed

    private void fnameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameTextFieldKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_fnameTextFieldKeyReleased

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void ageTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyPressed
        // TODO add your handling code here:

        String age = ageTextField.getText();
        int length = age.length();
        char c = evt.getKeyChar();

        if (evt.getKeyChar()>='0' && evt.getKeyChar()>'3'){
            if(length<3){
                ageTextField.setEditable(true);

            }
            else {
                ageTextField.setEditable(false);
            }
        }

    }//GEN-LAST:event_ageTextFieldKeyPressed

    private void emailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldKeyPressed

    private void msgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgTextFieldActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES","jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog (null);

        if (showOpenDialogue == JFileChooser. APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);

            ImageIcon icon = new ImageIcon(selectedImagePath);
            Image image = icon.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

            imageLabel.setIcon(new ImageIcon(image));

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         // TODO add your handling code here:

            
        
        String fname = fnameTextField.getText().trim();
        String lname = lnameTextField.getText().trim();
        String ageText = ageTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String msg = msgTextField.getText().trim();

        
         patient = new Patient();
            patient.setFname(fname);
            patient.setLname(lname);
            patient.setAgeText(ageText);
            patient.setEmail(email);
            patient.setMsg(msg);
            
            
            
            
        
        if (fname.isEmpty() || lname.isEmpty() || ageText.isEmpty() || email.isEmpty() || msg.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else {

            try {

                int age = Integer.parseInt(ageText);
                if (age < 0 || age > 100) {
                    JOptionPane.showMessageDialog(null, "Age must be between 0 and 100", "Error",
                        JOptionPane.ERROR_MESSAGE);
                }

                else {

                    String emailPattern = "^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$";
                    if (!email.matches(emailPattern)) {
                        JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    }
                    if(imageLabel.getIcon() == null){
                        JOptionPane.showMessageDialog(null, "Please Upload an Image", "Error",
                            JOptionPane.ERROR_MESSAGE);
                    }

          
                    
                    else {
                        String successMessage = "Registration Successful";

                        JPanel messagePanel = new JPanel(new BorderLayout());
                        JLabel successLabel = new JLabel(successMessage, SwingConstants.CENTER);

                        ImageIcon imageIcon = (ImageIcon) imageLabel.getIcon();
                        JLabel imageLabelInPopup = new JLabel(imageIcon);
                        messagePanel.add(successLabel, BorderLayout.NORTH);
                        messagePanel.add(imageLabelInPopup, BorderLayout.CENTER);

                        JOptionPane.showMessageDialog(null, messagePanel, "Success", JOptionPane.INFORMATION_MESSAGE);

                
                    
                    }
                    
                    
                     Date selectedDate = jDateChooser1.getDate();
 if (selectedDate == null) {
       
        JOptionPane.showMessageDialog(null, "Please select a date of birth", "Error", JOptionPane.ERROR_MESSAGE);
    } 
                    
                    
                    
                    
                }
                
                
                ViewPanel viewPanel = new ViewPanel(patient);
                bottomPanel.add(viewPanel);
                CardLayout layout = (CardLayout) bottomPanel.getLayout();
                layout.next(bottomPanel);
//                jSplitPane1.setBottomComponent(viewPanel);
                
            }
            
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid age", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        }
        
        

    }//GEN-LAST:event_submitButtonActionPerformed

    private void lnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTextFieldActionPerformed

    private void submitButtonVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_submitButtonVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonVetoableChange
public Patient getPatient() {
        return patient;
    }
//private javax.swing.JPanel bottomPanel;
//private javax.swing.JSplitPane jSplitPane1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField msgTextField;
    private javax.swing.JComboBox<String> patientTypeComboBox;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
